<!DOCTYPE html>
<html lang="en">
<head>

    <title>Login</title>
</head>
<body>
   <form action="/login" method="post" >
       Login <input type="text" name="username">
       <br>
       Password <input type="password" name="password">
       <br>
       <input type="submit" value="sign in">
       <br>
   </form>

   <a href="/registration_client"> <h2> Registration client </h2> </a>
   <a href="/registration_distributor"> <h2> Registration distributor </h2> </a>

</body>
</html>