<!DOCTYPE html>
<html lang="en">
<head>

    <title>Menu</title>
<!--    <link rel="stylesheet" href="/static/css/style.css">-->

    <link rel="stylesheet" href="../static/css/style.css" th:href="@{/css/style.css}">

</head>

<body>
<h2> Menu </h2>
<br>
<!--<a href="products/product_category/">Раздел товаров</a>-->
<a href="menu/products/product_category/">Раздел товаров</a>
<a href="/baskets/baskets">Операции с корзинами</a>

</body>
</html>